name: Snapshots

on:
  workflow_dispatch:
  push:
    branches: [ 2025.1.x ]

permissions: read-all

jobs:
  verify:
    name: Verify artifacts with BOM client
    runs-on: ${{ vars.ACTION_RUNNER || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java and Maven
        uses: spring-projects/spring-data-build/actions/setup-maven@4.0.x
        with:
          java-version: 'main'
          develocity-access-key: ''
      - name: Verify Artifacts with BOM client
        if: ${{ github.repository_owner == 'spring-projects' }}
        uses: spring-projects/spring-data-build/actions/maven-build@3.5.x
        env:
          OSS_ARTIFACTORY_USR: '${{ secrets.ARTIFACTORY_USERNAME }}'
          OSS_ARTIFACTORY_PSW: '${{ secrets.ARTIFACTORY_PASSWORD }}'
          COMMERCIAL_ARTIFACTORY_USR: '${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}'
          COMMERCIAL_ARTIFACTORY_PSW: '${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}'
        with:
          additional-options: '-Ddevelocity.cache.local.enabled=false -Ddevelocity.cache.remove.enabled=false -Pwith-bom-client'
          settings-xml: '${{ vars.SETTINGS_XML }}'
  build-snapshots:
    name: Build and deploy snapshots
    runs-on: ${{ vars.ACTION_RUNNER || 'ubuntu-latest' }}
    needs: verify
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java and Maven
        uses: spring-projects/spring-data-build/actions/setup-maven@4.0.x
        with:
          java-version: 'main'
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'
      - name: Deploy to Artifactory
        if: ${{ github.repository_owner == 'spring-projects' }}
        uses: spring-projects/spring-data-build/actions/maven-artifactory-deploy@4.0.x
        env:
          OSS_ARTIFACTORY_USR: '${{ secrets.ARTIFACTORY_USERNAME }}'
          OSS_ARTIFACTORY_PSW: '${{ secrets.ARTIFACTORY_PASSWORD }}'
          COMMERCIAL_ARTIFACTORY_USR: '${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}'
          COMMERCIAL_ARTIFACTORY_PSW: '${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}'
        with:
          build-name: 'spring-data-bom'
          additional-options: '-Ddevelocity.cache.local.enabled=false -Ddevelocity.cache.remove.enabled=false'
          settings-xml: '${{ vars.SETTINGS_XML }}'
